name: CI Pipeline

on:
  push:
    branches: [ "main", "develop", "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pnpm
        run: npm install -g pnpm@11.9.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Workspaces
        run: pnpm build
